version: 0.2

phases:
  build:
    commands:
      - echo "Connecting to EC2 instance"
      - chmod 400 ec2.pem
      - ssh -v -o "StrictHostKeyChecking no" -i ec2.pem ubuntu@ec2-13-201-28-33.ap-south-1.compute.amazonaws.com
      - ls
      - echo "Navigating to project directory"
      - sudo su
      - ls
      - cd django-documentation
      - echo "Pulling latest changes from Git"
      - git pull
      - echo "Building Docker image"
      - docker-compose -f docker-compose.prod.yml up --build
      - echo "Done."
