version: 0.2

phases:
  build:
    commands:
      - echo "Connecting to EC2 instance"
      - chmod 400 ec2.pem
      - ssh -v -o "StrictHostKeyChecking no" -i ec2.pem ubuntu@ec2-13-201-28-33.ap-south-1.compute.amazonaws.com 'bash -s' < deploy.sh
      - echo "Done."
