version: '3'

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate && gunicorn my_project.asgi:application --bind 0.0.0.0:8000 & celery -A my_project worker -l info -P gevent & celery -A my_project beat -l info"
    expose:
      - 8000
    volumes:
      - static_volume:/app/static_collected/
      - ./assets:/app/assets
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  nginx:
    build: ./infrastructure/setup/nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/app/static_collected/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - django

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

volumes:
  static_volume:
