# Generated by Django 4.2 on 2024-04-06 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_address_line1', models.CharField(max_length=150)),
                ('sender_address_line2', models.CharField(blank=True, max_length=150, null=True)),
                ('sender_country', models.CharField(max_length=150)),
                ('invoice_number', models.CharField(max_length=50)),
                ('order_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_address_line1', models.CharField(max_length=150)),
                ('recipient_address_line2', models.CharField(blank=True, max_length=150, null=True)),
                ('recipient_country', models.CharField(max_length=150)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('shipping_type', models.CharField(max_length=100)),
                ('payment_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.invoice')),
            ],
        ),
    ]
