# Generated by Django 4.2 on 2024-04-06 04:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_color', models.CharField(default='Blue', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('dob', models.DateField()),
                ('tob', models.TimeField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('ip_address', models.GenericIPAddressField()),
                ('slug', models.SlugField()),
                ('website', models.URLField()),
                ('identity', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hair_styled', models.BooleanField(default=False)),
                ('hair_length_cm', models.IntegerField(default=0)),
                ('hair_color_intensity', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('hair_shine_factor', models.FloatField(default=0.0)),
                ('hair_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FullData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hair_color', models.CharField(blank=True, choices=[('BL', 'Blonde'), ('BR', 'Brown'), ('BK', 'Black'), ('RD', 'Red'), ('OT', 'Other')], max_length=2)),
                ('duration', models.DurationField()),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('color', models.ManyToManyField(to='dashboard.color')),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.data')),
                ('hair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.hair')),
            ],
        ),
    ]
